#!/usr/bin/env bash
# Installs Nginx with the following configurations:
## server
## Nginx should be listening on port 80
## When querying Nginx at its root / with a GET request (requesting a page)\
### using curl, it must return a page that contains the string Hello World!
## As an answer file, write a Bash script that configures a new Ubuntu machine\
### to respect above requirements (this script will be run on the server itself)
## You can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
