#!/usr/bin/env bash
# Installs Nginx with the following configurations:
## server
## Nginx should be listening on port 80
## When querying Nginx at its root / with a GET request (requesting a page)\
### using curl, it must return a page that contains the string Hello World!
## As an answer file, write a Bash script that configures a new Ubuntu machine\
### to respect above requirements (this script will be run on the server itself)
## You can’t use systemctl for restarting nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html

sed -i "listen 80;\ns/server_name _;/server_name _;\n\tlocation ^\/redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4};/" /etc/nginx/sites-available/default
service nginx start