#!/usr/bin/env bash
# 404 Not Found Page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
